# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.20"
  amd64: "ghcr.io/homeassistant/amd64-base-python:3.13-alpine3.20"
  armhf: "ghcr.io/homeassistant/armhf-base-python:3.13-alpine3.20"
  armv7: "ghcr.io/homeassistant/armv7-base-python:3.13-alpine3.20"
  i386: "ghcr.io/homeassistant/i386-base-python:3.13-alpine3.20"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: LoRa2MQTT"
  org.opencontainers.image.description: "Connection between LoRa devices with Home Assistant using MQTT."
  org.opencontainers.image.source: "https://github.com/leofig-rj/leofig-hass-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
