# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "home-assistant/aarch64-base-python:3.9-alpine3.16"
  amd64: "homeassistant/amd64-base-python"
  armhf: "homeassistant/armhf-base-python:3.8-alpine3.13"
  armv7: "homeassistant/armv7-base-python:3.8-alpine3.13"
  i386: "homeassistant/i386-base-python"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: LoRa2MQTT"
  org.opencontainers.image.description: "Connection between LoRa devices with Home Assistant using MQTT."
  org.opencontainers.image.source: "https://github.com/leofig-rj/leofig-hass-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
