# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: LoRa2MQTT
version: "0.0.1"
slug: lora2mqtt
description: Connection between LoRa devices and Home Assistant using MQTT
url: "https://github.com/leofig-rj/leofig-hass-addons"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
services:
  - mqtt:need
uart: true               # Habilita o acesso à uart do OS
udev: true               # Habilita o acesso à udev do OS para monitorar USB
homeassistant_api: true  # Habilita o acesso à API do Home Assistant
host_network: true       # Permite o uso da rede do host
map:
  config: false           # Permite acesso à pasta /config
map:
  - type: share
    read_only: false
  - type: homeassistant_config
    read_only: false
    path: /config
  - type: addon_config
    read_only: false
    path: /addon_config
options:
  serial:
    port: "/dev/ttyACM0"
  log_level: "INFO"
schema:
  serial:
    port: "str"
    baudrate: "int?"
    rtscts": "bool?"
  log_level: "list(DEBUG|INFO|WARNING|ERROR)?"
  data_path: "str?"
  max_threads: "int?"
      "type": "homeassistant_config",
      "read_only": false,
      "path": "/config"
