# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: LoRa2MQTT
version: "0.1"
slug: lora2mqtt
description: Connection between LoRa devices with Home Assistant using MQTT
url: "https://github.com/leofig-rj/leofig-hass-addons"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
services:
  - mqtt:need
init: false
map:
  - share:rw
options:
  homeassistantprefix: "homeassistant"
  chipmac: "123456789012"
  loraslaveaddrs: 2
  loraslavenames: "Eletricidade"
  loraslavemacs: "234567890123"
  loraslavevers: "Ver 1.1"
  loraslavechips: "ESP32"
  loglevel: "INFO"
schema:
  homeassistantprefix: "str"
  chipmac: "str"
  loraslaveaddrs: "int"
  loraslavenames: "str"
  loraslavemacs: "str"
  loraslavevers: "str"
  loraslavechips: "str"
  loglevel: "list(DEBUG|INFO|WARNING|ERROR)?"
  maxthreads: "int?"
