# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: LoRa2MQTT
version: "0.0.1"
slug: lora2mqtt
description: Connection between LoRa devices and Home Assistant using MQTT
url: "https://github.com/leofig-rj/leofig-hass-addons"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
services:
  - mqtt:need
uart: true               # Habilita o acesso à uart do OS
udev: true               # Habilita o acesso à udev do OS para monitorar USB
homeassistant_api: true  # Habilita o acesso à API do Home Assistant
host_network: true       # Permite o uso da rede do host
map:
  share: true          # Permite acesso à pasta /share
  coonfig: true        # Permite acesso à pasta /config
options:
  homeassistantprefix: "homeassistant"
  chipmac: "123456789012"
  loraslaveaddrs: "2,3"
  loraslavenames: "Eletricidade,Luz"
  loraslavemacs: "234567890123,345678901234"
  loraslavevers: "Ver_1.1,Ver_2.2"
  loraslavechips: "ESP32,ESP8266"
  serial:
    port: "/dev/ttyACM0"
  loglevel: "INFO"
  data_path: "/config/lora2mqtt"
schema:
  homeassistantprefix: "str"
  chipmac: "str"
  loraslaveaddrs: "str"
  loraslavenames: "str"
  loraslavemacs: "str"
  loraslavevers: "str"
  loraslavechips: "str"
  serial:
    port: "str?"
    adapter: "match(zstack|deconz|zigate|ezsp|ember|zboss)?"
    baudrate: "int?"
    rtscts": "bool?"
  loglevel: "list(DEBUG|INFO|WARNING|ERROR)?"
  data_path: "str"
  maxthreads: "int?"
