# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: LoRa2MQTT
version: "0.1"
slug: lora2mqtt
description: Connection between LoRa devices with Home Assistant using MQTT
url: "https://github.com/leofig-rj/leofig-hass-addons"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
services:
  - mqtt:need
init: false
map:
  - share:rw
options:
  ttlockclientid: "TTLOCK CLOUD CLIENT ID"
  ttlockclientsecret: "TTLOCK CLOUD CLIENT SECRET"
  ttlockuser: "TTLOCK CLOUD USER"
  ttlockhash: "TTLOCK CLOUD HASH"
  publishstatedelay: 60
  publishstatedelayshort: 15
  publishbatterydelay: 3600
  loglevel: "INFO"
schema:
  ttlockclientid: "str"
  ttlockclientsecret: "str"
  ttlockuser: "str"
  ttlockhash: "str"
  publishstatedelay: "int?"
  publishstatedelayshort: "int?"
  publishbatterydelay: "int?"
  loglevel: "list(DEBUG|INFO|WARNING|ERROR)?"
  maxthreads: "int?"
