# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: LoRa2MQTT
version: "0.1"
slug: lora2mqtt
description: Connection between LoRa devices and Home Assistant using MQTT
url: "https://github.com/leofig-rj/leofig-hass-addons"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
services:
  - mqtt:need
init: false
map:
  - share:rw
options:
  homeassistantprefix: "homeassistant"
  lora_slave_addrs:
    - 2
    - 3
  lora_slave_names:
    - "Eletricidade"
    - "Luz"  chipmac: "123456789012"
  loraslavemacs:
    - "234567890123"
    - "345678901234"
  loraslavevers:
    - "Ver 1.1"
    - "Ver 2.2"
  loraslavechips:
    - "ESP32"
    - "ESP8266"
  loglevel: "INFO"
schema:
  homeassistantprefix: "str"
  chipmac: "str"
  lora_slave_addrs: 
    - "int"
  lora_slave_names: 
    - "str"
  loraslavemacs:
    - "str"
  loraslavevers:
    - "str"
  loraslavechips:
    - "str"
  loglevel: "list(DEBUG|INFO|WARNING|ERROR)?"
  maxthreads: "int?"
