# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: LoRa2MQTT
version: "0.1"
slug: lora2mqtt
description: Connection between LoRa devices with Home Assistant using MQTT
url: "https://github.com/leofig-rj/leofig-hass-addons"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
services:
  - mqtt:need
init: false
map:
  - share:rw
options:
  home_assistant_prefix: "homeassistant"
  chip_mac: "123456789012"
  lora_slave_addrs: [2,3]
  lora_slave_names: ["Eletricidade", "Luz"]
  lora_slave_macs: ["234567890123", "345678901234"]
  lora_slave_vers: ["Ver 1.1", "Ver 2.2"]
  lora_slave_chips: ["ESP32", "ESP8266"]
  loglevel: "INFO"
schema:
  home_assistant_prefix: "str"
  chip_mac: "str"
  lora_slave_addrs: "list"
  lora_slave_names: "list"
  lora_slave_macs: "list"
  lora_slave_vers: "list"
  lora_slave_chips: "list"
  loglevel: "list(DEBUG|INFO|WARNING|ERROR)?"
  maxthreads: "int?"
