# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: LoRa2MQTT
version: "0.0.1"
slug: lora2mqtt
description: Connection between LoRa devices and Home Assistant using MQTT
url: "https://github.com/leofig-rj/leofig-hass-addons"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
services:
  - mqtt:need
init: false
map:
  - share:rw
options:
  homeassistantprefix: "homeassistant"
  chipmac: "123456789012"
  loraslaveaddrs: "2,3"
  loraslavenames: "Eletricidade,Luz"
  loraslavemacs: "234567890123,345678901234"
  loraslavevers: "Ver_1.1,Ver_2.2"
  loraslavechips: "ESP32,ESP8266"
  loglevel: "INFO"
  serialport: "/dev/ttyACM0"
schema:
  homeassistantprefix: "str"
  chipmac: "str"
  loraslaveaddrs: "str"
  loraslavenames: "str"
  loraslavemacs: "str"
  loraslavevers: "str"
  loraslavechips: "str"
  loglevel: "list(DEBUG|INFO|WARNING|ERROR)?"
  serialport: str
  maxthreads: "int?"
devices:
  - "{serialport}:{serialport}"